version: "3.9"

services:
  dotnet:
    build:
      context: .
      dockerfile: Dockerfile
    command: sleep infinity
    volumes:
      - ..:/workspaces/dotnet
    # This is where ports would go
    networks:
      - dotnet-network
  # Additional services here
# Volumes here
networks:
  dotnet-network:
    driver: bridge
    